spring:
  datasource:
    url: jdbc:mysql://localhost:3306/air_tickets
    username: bestuser
    password: bestuser
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
  mvc:
    format:
      date: iso

springdoc:
  swagger-ui:
    path: /api/docs.html

vaadin:
  exclude-urls: /api/**