spring:
  datasource:
    url: jdbc:mysql://localhost:3306/air_tickets
    username: bestuser
    password: bestuser
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  mvc:
    format:
      date: iso

app:
  admin:
    username: admin
    password: admin
    email: admin@example.com